import apps from './apps.json'

export function getAllApps() {
  return apps
}

export function getAppBySlug(slug) {
  return apps.find(app => app.slug === slug) || null
}

export function getAppsByCategory(category) {
  return apps.filter(app => app.category === category)
}

export function getRelatedApps(currentSlug, category, limit = 4) {
  return apps
    .filter(app => app.slug !== currentSlug && app.category === category)
    .slice(0, limit)
}

export function getCategories() {
  return [...new Set(apps.map(app => app.category))]
}

export function searchApps(query) {
  const q = query.toLowerCase()
  return apps.filter(app =>
    app.name.toLowerCase().includes(q) ||
    app.category.toLowerCase().includes(q) ||
    app.keywords.some(k => k.includes(q))
  )
}

export function renderStars(rating) {
  const full = Math.floor(rating)
  const half = rating % 1 >= 0.5 ? 1 : 0
  const empty = 5 - full - half
  return { full, half, empty }
}


export function getAllQueryKeywords() {
  return [
  "Love Rummy",
  "Love Rummy Yono App",
  "Love Rummy New Yono App",
  "Love Rummy Yono Game",
  "Love Rummy Yono",
  "Love Rummy Payment",
  "Love Rummy Download",
  "Love Rummy LinkAll New Yono Games",
  "All App Yono",
  "Best Earning Apps",
  "All Yono App",
  "Best Earning Apps All Yono Games",
  "Yono All Games",
  "New Yono App",
  "New Yono Games",
  "All Yono Apps",
  "Yono Rummy",
  "Yono Games",
  "Yono Slots",
  "New Upcoming Yono App",
  "Yono Rummy App",
  "All Best Yono App",
  "Top 10 Rummy Apps",
  "All Rummy App",
  "All Best Rummy Apps",
  "All Yono Appps",
  "Yono All App",
  "Yono 51 Bonus",
  "New Yono Apps",
  "All Yono App List 51 Bonus",
  "All Yono",
  "Yono All",
  "All Yono App List 41 Bonus",
  "Yono List",
  "All Yono App List",
  "Yono All Apk",
  "Yono Apps List",
  "Yono 51 Apk",
  "Yono Bonus 51 Rupees Free",
  "All Yono Games",
  "All Yono Game",
  "Yono All Game",
  "Yono Game List",
  "Yono 41 Bonus",
  "All Yono Apk",
  "Yono Apk All",
  "All Yono App 51 Bonus",
  "All Yono App Link",
  "All Yono Store",
  "Best Yono App",
  "All Yono App List 2024",
  "Top Yono App",
  "Yono App List",
  "Yono Bonus App Download",
  "All New Yono App",
  "Dragon Vs Tiger",
  "all yono app 2023",
  "all yono app 2024",
  "all rummy game 2024",
  "all Yono game 551 bonus",
  "all yono games 2024",
  "all yono games 551 bonus",
  "all yono games online",
  "new yono app 551 bonus",
  "new yono apps 2023",
  "Best Earning Apps yono all apk 551 bonus",
  "yono all app 2023",
  "yono all app 2024",
  "yono all app new 2024",
  "yono all games 2023",
  "yono all games 2024",
  "yono slots",
  "yono new app 2024 download",
  "yono new app 51 bonus 2024",
  "teen patti gold 51 bonus",
  "new rum my app 500 bonus",
  "rummy all app 2024",
  "all yono game 2024",
  "Best Earning Apps yono all app new 2024",
  "all yono games 500 bonus",
  "new yono apps 2024",
  "new yono app 500 bonus",
  "all yono games 550 bonus",
  "all rummy app 2024",
  "all yono game 550 bonus",
  "yono download",
  "111 yono 51 bonus",
  "all best yono app",
  "all yono",
  "all yono 51 bonus",
  "all yono app link",
  "all yono app list 2024",
  "all yono app list 51 bonus",
  "all yono application",
  "all yono game list",
  "all yono games",
  "best yono app",
  "go rummy",
  "holy rummy apk",
  "new yono app",
  "new yono app 2023",
  "new rummy app 2023 500 bonus",
  "new yono app 2023 51 bonus",
  "new yono app 2023 list",
  "new rummy app 2024",
  "new yono app 2024 51 bonus download",
  "royally rummy",
  "yono 100 rupees free",
  "yono 41 bonus",
  "yono 51",
  "yono 51 apk",
  "yono 51 bonus",
  "yono all app",
  "yono all apps",
  "yono apk download",
  "rummy best",
  "rummy best app",
  "rummy bonus",
  "rummy bonus 50 rupees free",
  "rummy download",
  "rummy earning",
  "rummy game",
  "rummy golds",
  "yono list",
  "yono list 2024",
  "New Yono App Bonus ₹51",
  "Rummy 365",
  "En 365",
  "101z",
  "Spin 101",
  "Ind Bingo",
  "My 777",
  "Bet 213",
  "GoGo Rummy",
  "Bingo 101",
  "789 Jackpots",
  "Spin Gold",
  "Spin 777",
  "Spin Lucky",
  "Mdm Bet",
  "Ind Slots",
  "Spin Crush",
  "MBM Bet",
  "MKM BET",
  "Slots Winner",
  "Spin Winner",
  "Yono VIP",
  "567 Slots",
  "Yono Arcade",
  "Yono 777",
  "Yono apps",
  "Yono app list",
  "Best Yono apps",
  "rummy list",
  "rummy list 2023",
  "rummy mars",
  "rummy master",
  "rummy modern apk",
  "rummy nabob",
  "rummy new app 2024 download",
  "rummy new app 51 bonus 2024",
  "rummy wealth",
  "rummy wealth 555",
  "rummy win",
  "teen patti 51 bonus",
  "top 20 yono 51 bonus",
  "top yono",
  "top yono app",
  "All Rummy Application",
  "Rummy All App",
  "Rummy 51 Bonus",
  "New Rummy Apps",
  "All Rummy App List 51 Bonus",
  "All Rummy",
  "Rummy All",
  "All Rummy App List 41 Bonus",
  "Rummy List",
  "All Rummy App List",
  "Rummy All Apk",
  "Rummy Apps List",
  "Rummy 51 Apk",
  "Rummy Bonus 51 Rupees Free",
  "All Rummy Games",
  "All Rummy Game",
  "Rummy All Game",
  "Rummy All Games",
  "Rummy Game List",
  "Rummy 41 Bonus",
  "All Rummy Apk",
  "Rummy Apk All",
  "All Rummy App 51 Bonus",
  "All Rummy App Link",
  "All Rummy Store",
  "Best Rummy App",
  "All Rummy App List 2024",
  "Top Rummy App",
  "Rummy App List",
  "Rummy Bonus App Download",
  "All App Rummy",
  "All New Rummy App",
  "All Best Rummy App",
  "all rummy app 2023",
  "all rummy game 500 bonus",
  "all rummy games 2024",
  "all rummy games 500 bonus",
  "all rummy games online",
  "new rummy app 151 bonus",
  "new rummy apps 2023",
  "rummy all apk 151 bonus",
  "rummy all app new 2024",
  "rummy all games 2023",
  "rummy all games 2024",
  "rummy gold",
  "new rummy app 500 bonus",
  "all rummy games 551 bonus",
  "rummy all app 2023",
  "111 rummy 51 bonus",
  "all best rummy app",
  "all rummy",
  "all rummy 51 bonus",
  "all rummy app link",
  "all rummy app list 2024",
  "all rummy app list 51 bonus",
  "all rummy application",
  "rummy apk",
  "new rummy app",
  "new rummy app 2023",
  "new rummy app 2023 51 bonus",
  "new rummy app 2024 51 bonus download",
  "rummy 100 rupees free",
  "rummy 41 bonus",
  "rummy 51",
  "rummy 51 apk",
  "rummy 51 bonus",
  "top 20 rummy 51 bonus",
  "top rummy",
  "top rummy app",
  "Yono Bonus",
  "Yono Bonus download",
  "Yono Bonus play",
  "Yono Bonus login",
  "Yono Bonus APK",
  "Yono Bonus bonus",
  "Yono Bonus withdrawal",
  "Yono All Games download",
  "Yono All Games play",
  "Yono All Games login",
  "Yono All Games APK",
  "Yono All Games bonus",
  "Yono All Games withdrawal",
  "All Rummy Apps",
  "All Rummy Apps download",
  "All Rummy Apps play",
  "All Rummy Apps login",
  "All Rummy Apps APK",
  "All Rummy Apps bonus",
  "All Rummy Apps withdrawal",
  "New Yono App download",
  "New Yono App play",
  "New Yono App login",
  "New Yono App APK",
  "New Yono App bonus",
  "New Yono App withdrawal",
  "Yono App",
  "Yono App download",
  "Yono App play",
  "Yono App login",
  "Yono App APK",
  "Yono App bonus",
  "Yono App withdrawal",
  "Rummy App",
  "Rummy App download",
  "Rummy App play",
  "Rummy App login",
  "Rummy App APK",
  "Rummy App bonus",
  "Rummy App withdrawal",
  "Yono Games download",
  "Yono Games play",
  "Yono Games login",
  "Yono Games APK",
  "Yono Games bonus",
  "Yono Games withdrawal",
  "Yono Game",
  "Yono Game download",
  "Yono Game play",
  "Yono Game login",
  "Yono Game APK",
  "Yono Game bonus",
  "Yono Game withdrawal",
  "INR SLOTS",
  "INR SLOTS download",
  "INR SLOTS play",
  "INR SLOTS login",
  "INR SLOTS APK",
  "INR SLOTS bonus",
  "INR SLOTS withdrawal",
  "Bingo 101 download",
  "Bingo 101 play",
  "Bingo 101 login",
  "Bingo 101 APK",
  "Bingo 101 bonus",
  "Bingo 101 withdrawal",
  "Yono Rummy download",
  "Yono Rummy play",
  "Yono Rummy login",
  "Yono Rummy APK",
  "Yono Rummy bonus",
  "Yono Rummy withdrawal",
  "Yono Arcade download",
  "Yono Arcade play",
  "Yono Arcade login",
  "Yono Arcade APK",
  "Yono Arcade bonus",
  "Yono Arcade withdrawal",
  "Yono Slots download",
  "Yono Slots play",
  "Yono Slots login",
  "Yono Slots APK",
  "Yono Slots bonus",
  "Yono Slots withdrawal",
  "Yono VIP download",
  "Yono VIP play",
  "Yono VIP login",
  "Yono VIP APK",
  "Yono VIP bonus",
  "Yono VIP withdrawal",
  "567 Slots download",
  "567 Slots play",
  "567 Slots login",
  "567 Slots APK",
  "567 Slots bonus",
  "567 Slots withdrawal",
  "MBM Bet download",
  "MBM Bet play",
  "MBM Bet login",
  "MBM Bet APK",
  "MBM Bet bonus",
  "MBM Bet withdrawal",
  "Spin Winner download",
  "Spin Winner play",
  "Spin Winner login",
  "Spin Winner APK",
  "Spin Winner bonus",
  "Spin Winner withdrawal",
  "Slots Winner download",
  "Slots Winner play",
  "Slots Winner login",
  "Slots Winner APK",
  "Slots Winner bonus",
  "Slots Winner withdrawal",
  "MkM Bet",
  "MkM Bet download",
  "MkM Bet play",
  "MkM Bet login",
  "MkM Bet APK",
  "MkM Bet bonus",
  "MkM Bet withdrawal",
  "Spin Crush download",
  "Spin Crush play",
  "Spin Crush login",
  "Spin Crush APK",
  "Spin Crush bonus",
  "Spin Crush withdrawal",
  "IND Slots",
  "IND Slots download",
  "IND Slots play",
  "IND Slots login",
  "IND Slots APK",
  "IND Slots bonus",
  "IND Slots withdrawal",
  "Spin 777 download",
  "Spin 777 play",
  "Spin 777 login",
  "Spin 777 APK",
  "Spin 777 bonus",
  "Spin 777 withdrawal",
  "Spin Lucky download",
  "Spin Lucky play",
  "Spin Lucky login",
  "Spin Lucky APK",
  "Spin Lucky bonus",
  "Spin Lucky withdrawal",
  "Spin Gold download",
  "Spin Gold play",
  "Spin Gold login",
  "Spin Gold APK",
  "Spin Gold bonus",
  "Spin Gold withdrawal",
  "MDM Bet",
  "MDM Bet download",
  "MDM Bet play",
  "MDM Bet login",
  "MDM Bet APK",
  "MDM Bet bonus",
  "MDM Bet withdrawal",
  "789 Jackpot",
  "789 Jackpot download",
  "789 Jackpot play",
  "789 Jackpot login",
  "789 Jackpot APK",
  "789 Jackpot bonus",
  "789 Jackpot withdrawal",
  "GoGo Rummy download",
  "GoGo Rummy play",
  "GoGo Rummy login",
  "GoGo Rummy APK",
  "GoGo Rummy bonus",
  "GoGo Rummy withdrawal",
  "Bet213",
  "Bet213 download",
  "Bet213 play",
  "Bet213 login",
  "Bet213 APK",
  "Bet213 bonus",
  "Bet213 withdrawal",
  "Raja Luck",
  "Raja Luck download",
  "Raja Luck play",
  "Raja Luck login",
  "Raja Luck APK",
  "Raja Luck bonus",
  "Raja Luck withdrawal",
  "My777",
  "My777 download",
  "My777 play",
  "My777 login",
  "My777 APK",
  "My777 bonus",
  "My777 withdrawal",
  "Ind Bingo download",
  "Ind Bingo play",
  "Ind Bingo login",
  "Ind Bingo APK",
  "Ind Bingo bonus",
  "Ind Bingo withdrawal",
  "Spin101",
  "Spin101 download",
  "Spin101 play",
  "Spin101 login",
  "Spin101 APK",
  "Spin101 bonus",
  "Spin101 withdrawal",
  "Rummy 365 download",
  "Rummy 365 play",
  "Rummy 365 login",
  "Rummy 365 APK",
  "Rummy 365 bonus",
  "Rummy 365 withdrawal",
  "101Z App",
  "101Z App download",
  "101Z App play",
  "101Z App login",
  "101Z App APK",
  "101Z App bonus",
  "101Z App withdrawal",
  "EN 365",
  "EN 365 download",
  "EN 365 play",
  "EN 365 login",
  "EN 365 APK",
  "EN 365 bonus",
  "EN 365 withdrawal",
  "MWM Bet",
  "MWM Bet download",
  "MWM Bet play",
  "MWM Bet login",
  "MWM Bet APK",
  "MWM Bet bonus",
  "MWM Bet withdrawal",
  "JaiHo Spin",
  "JaiHo Spin download",
  "JaiHo Spin play",
  "JaiHo Spin login",
  "JaiHo Spin APK",
  "JaiHo Spin bonus",
  "JaiHo Spin withdrawal",
  "JaiHo Rummy",
  "JaiHo Rummy download",
  "JaiHo Rummy play",
  "JaiHo Rummy login",
  "JaiHo Rummy APK",
  "JaiHo Rummy bonus",
  "JaiHo Rummy withdrawal",
  "Rummy 91",
  "Rummy 91 download",
  "Rummy 91 play",
  "Rummy 91 login",
  "Rummy 91 APK",
  "Rummy 91 bonus",
  "Rummy 91 withdrawal",
  "Neta VIP",
  "Neta VIP download",
  "Neta VIP play",
  "Neta VIP login",
  "Neta VIP APK",
  "Neta VIP bonus",
  "Neta VIP withdrawal",
  "Jaiho 777",
  "Jaiho 777 download",
  "Jaiho 777 play",
  "Jaiho 777 login",
  "Jaiho 777 APK",
  "Jaiho 777 bonus",
  "Jaiho 777 withdrawal",
  "JaiHo Arcade",
  "JaiHo Arcade download",
  "JaiHo Arcade play",
  "JaiHo Arcade login",
  "JaiHo Arcade APK",
  "JaiHo Arcade bonus",
  "JaiHo Arcade withdrawal",
  "ABC Rummy",
  "ABC Rummy download",
  "ABC Rummy play",
  "ABC Rummy login",
  "ABC Rummy APK",
  "ABC Rummy bonus",
  "ABC Rummy withdrawal",
  "Saga Slots",
  "Saga Slots download",
  "Saga Slots play",
  "Saga Slots login",
  "Saga Slots APK",
  "Saga Slots bonus",
  "Saga Slots withdrawal",
  "MQM Bet",
  "MQM Bet download",
  "MQM Bet play",
  "MQM Bet login",
  "MQM Bet APK",
  "MQM Bet bonus",
  "MQM Bet withdrawal",
  "Slots Spin",
  "Slots Spin download",
  "Slots Spin play",
  "Slots Spin login",
  "Slots Spin APK",
  "Slots Spin bonus",
  "Slots Spin withdrawal",
  "Ind Rummy",
  "Ind Rummy download",
  "Ind Rummy play",
  "Ind Rummy login",
  "Ind Rummy APK",
  "Ind Rummy bonus",
  "Ind Rummy withdrawal",
  "TOP Rummy",
  "TOP Rummy download",
  "TOP Rummy play",
  "TOP Rummy login",
  "TOP Rummy APK",
  "TOP Rummy bonus",
  "TOP Rummy withdrawal",
  "Jaiho Slots",
  "Jaiho Slots download",
  "Jaiho Slots play",
  "Jaiho Slots login",
  "Jaiho Slots APK",
  "Jaiho Slots bonus",
  "Jaiho Slots withdrawal",
  "IND Club",
  "IND Club download",
  "IND Club play",
  "IND Club login",
  "IND Club APK",
  "IND Club bonus",
  "IND Club withdrawal",
  "Jaiho Win",
  "Jaiho Win download",
  "Jaiho Win play",
  "Jaiho Win login",
  "Jaiho Win APK",
  "Jaiho Win bonus",
  "Jaiho Win withdrawal",
  "Hi Rummy",
  "Hi Rummy download",
  "Hi Rummy play",
  "Hi Rummy login",
  "Hi Rummy APK",
  "Hi Rummy bonus",
  "Hi Rummy withdrawal",
  "Maha Games",
  "Maha Games download",
  "Maha Games play",
  "Maha Games login",
  "Maha Games APK",
  "Maha Games bonus",
  "Maha Games withdrawal",
  "Share Slots",
  "Share Slots download",
  "Share Slots play",
  "Share Slots login",
  "Share Slots APK",
  "Share Slots bonus",
  "Share Slots withdrawal",
  "Love Rummy download",
  "Love Rummy play",
  "Love Rummy login",
  "Love Rummy APK",
  "Love Rummy bonus",
  "Love Rummy withdrawal",
  "Yes Spin",
  "Yes Spin download",
  "Yes Spin play",
  "Yes Spin login",
  "Yes Spin APK",
  "Yes Spin bonus",
  "Yes Spin withdrawal",
  "Club INR",
  "Club INR download",
  "Club INR play",
  "Club INR login",
  "Club INR APK",
  "Club INR bonus",
  "Club INR withdrawal",
  "Hindi 777",
  "Hindi 777 download",
  "Hindi 777 play",
  "Hindi 777 login",
  "Hindi 777 APK",
  "Hindi 777 bonus",
  "Hindi 777 withdrawal",
  "Good Slots",
  "Good Slots download",
  "Good Slots play",
  "Good Slots login",
  "Good Slots APK",
  "Good Slots bonus",
  "Good Slots withdrawal",
  "OK Rummy",
  "OK Rummy download",
  "OK Rummy play",
  "OK Rummy login",
  "OK Rummy APK",
  "OK Rummy bonus",
  "OK Rummy withdrawal",
  "Ever 777",
  "Ever 777 download",
  "Ever 777 play",
  "Ever 777 login",
  "Ever 777 APK",
  "Ever 777 bonus",
  "Ever 777 withdrawal",
  "777.Game",
  "777.Game download",
  "777.Game play",
  "777.Game login",
  "777.Game APK",
  "777.Game bonus",
  "777.Game withdrawal",
  "Rummy Ludo",
  "Rummy Ludo download",
  "Rummy Ludo play",
  "Rummy Ludo login",
  "Rummy Ludo APK",
  "Rummy Ludo bonus",
  "Rummy Ludo withdrawal",
  "Rummy 77",
  "Rummy 77 download",
  "Rummy 77 play",
  "Rummy 77 login",
  "Rummy 77 APK",
  "Rummy 77 bonus",
  "Rummy 77 withdrawal",
  "Goa Spin",
  "Goa Spin download",
  "Goa Spin play",
  "Goa Spin login",
  "Goa Spin APK",
  "Goa Spin bonus",
  "Goa Spin withdrawal",
  "91 Club",
  "91 Club download",
  "91 Club play",
  "91 Club login",
  "91 Club APK",
  "91 Club bonus",
  "91 Club withdrawal",
  "Rani Slots",
  "Rani Slots download",
  "Rani Slots play",
  "Rani Slots login",
  "Rani Slots APK",
  "Rani Slots bonus",
  "Rani Slots withdrawal",
  "Rummy 888",
  "Rummy 888 download",
  "Rummy 888 play",
  "Rummy 888 login",
  "Rummy 888 APK",
  "Rummy 888 bonus",
  "Rummy 888 withdrawal",
  "Yono 777 download",
  "Yono 777 play",
  "Yono 777 login",
  "Yono 777 APK",
  "Yono 777 bonus",
  "Yono 777 withdrawal",
  "Boss Rummy",
  "Boss Rummy download",
  "Boss Rummy play",
  "Boss Rummy login",
  "Boss Rummy APK",
  "Boss Rummy bonus",
  "Boss Rummy withdrawal",
  "INR Rummy",
  "INR Rummy download",
  "INR Rummy play",
  "INR Rummy login",
  "INR Rummy APK",
  "INR Rummy bonus",
  "INR Rummy withdrawal",
  "DIWA 777",
  "DIWA 777 download",
  "DIWA 777 play",
  "DIWA 777 login",
  "DIWA 777 APK",
  "DIWA 777 bonus",
  "DIWA 777 withdrawal",
  "Joy Rummy",
  "Joy Rummy download",
  "Joy Rummy play",
  "Joy Rummy login",
  "Joy Rummy APK",
  "Joy Rummy bonus",
  "Joy Rummy withdrawal",
  "Rumble Rummy",
  "Rumble Rummy download",
  "Rumble Rummy play",
  "Rumble Rummy login",
  "Rumble Rummy APK",
  "Rumble Rummy bonus",
  "Rumble Rummy withdrawal",
  "Yn777",
  "Yn777 download",
  "Yn777 play",
  "Yn777 login",
  "Yn777 APK",
  "Yn777 bonus",
  "Yn777 withdrawal",
  "All Yono Games download",
  "All Yono Games play",
  "All Yono Games login",
  "All Yono Games APK",
  "All Yono Games bonus",
  "All Yono Games withdrawal",
  "Game Rummy",
  "Game Rummy download",
  "Game Rummy play",
  "Game Rummy login",
  "Game Rummy APK",
  "Game Rummy bonus",
  "Game Rummy withdrawal",
  "all new yono apps",
  "yono app download",
  "yono app login",
  "yono app play",
  "yono app apk",
  "yono app signup bonus",
  "rummy app download",
  "best yono apps 2026",
  "new yono apps 2026",
  "top yono games 2026",
  "best rummy apps 2026",
  "real cash rummy apps",
  "rummy app signup bonus"
];
}